# Generated by Django 4.1.3 on 2022-12-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.CharField(choices=[('violin', 'violin'), ('piano', 'piano'), ('giutar', 'guitar')], max_length=20)),
                ('number_of_lessons', models.CharField(choices=[('24', '24'), ('48', '48'), ('72', '72'), ('96', '96')], max_length=10)),
                ('interval', models.CharField(choices=[('1', '1 lesson every week'), ('2', '2 lessons every week')], max_length=20)),
                ('duration', models.CharField(choices=[('30', '30 minutes'), ('45', '45 minutes'), ('60', '60 minutes')], max_length=10)),
                ('teacher', models.CharField(max_length=20)),
            ],
        ),
    ]
