# Generated by Django 4.1.3 on 2022-12-06 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='teacher_id',
            field=models.CharField(choices=[], max_length=20),
        ),
    ]
