# Generated by Django 4.1.3 on 2022-12-03 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='title',
            new_name='teacher',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='teacher_id',
        ),
        migrations.AddField(
            model_name='lesson',
            name='interval',
            field=models.CharField(choices=[('1', '1 lesson every week'), ('2', '2 lessons every week')], default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='number_of_lessons',
            field=models.CharField(choices=[('24', '24'), ('48', '48'), ('72', '72'), ('96', '96')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='select_lesson',
            field=models.CharField(choices=[('violin', 'violin'), ('piano', 'piano'), ('giutar', 'guitar')], default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='start_date',
            field=models.DateTimeField(null=True, verbose_name='enter your start time'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='duration',
            field=models.CharField(choices=[('30', '30 minutes'), ('45', '45 minutes'), ('60', '60 minutes')], max_length=10),
        ),
    ]
