# Generated by Django 4.1.3 on 2022-12-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.CharField(max_length=20)),
                ('number_of_lessons', models.CharField(max_length=10)),
                ('interval', models.CharField(max_length=20)),
                ('duration', models.CharField(choices=[('30', '30 minutes'), ('45', '45 minutes'), ('60', '60 minutes')], max_length=10)),
                ('teacher', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
