# Generated by Django 4.1.3 on 2022-12-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_request_teacher_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='teacher_id',
            field=models.CharField(max_length=20),
        ),
    ]
