# Generated by Django 4.1.3 on 2022-12-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_request_availability'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Availability',
        ),
        migrations.AlterField(
            model_name='request',
            name='availability',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
