# Generated by Django 4.1.3 on 2022-12-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_request_delete_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='availibility',
            field=models.DateTimeField(null=True, verbose_name='enter your start time'),
        ),
    ]
