# Generated by Django 4.1.3 on 2022-12-04 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_user_is_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='select_lesson',
            new_name='instrument',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='start_date',
        ),
    ]
