# Generated by Django 4.1.3 on 2022-12-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_request_availibility'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='teacher',
            new_name='teacher_id',
        ),
        migrations.AlterField(
            model_name='request',
            name='availibility',
            field=models.DateField(null=True, verbose_name='enter your start time for the lessons (yyyy-mm-dd)'),
        ),
        migrations.AlterField(
            model_name='request',
            name='interval',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='number_of_lessons',
            field=models.IntegerField(),
        ),
    ]
