# Generated by Django 4.1.2 on 2022-11-22 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_rename_admin_teacher'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teacher',
            new_name='Admin',
        ),
    ]
