# Generated by Django 4.1.3 on 2022-12-04 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_rename_select_lesson_lesson_instrument_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='teacher',
            new_name='teacher_id',
        ),
        migrations.AddField(
            model_name='lesson',
            name='student_id',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
