# Generated by Django 4.1.3 on 2022-12-05 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_rename_teacher_request_teacher_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='teacher_id',
            new_name='teacher',
        ),
    ]
