# Generated by Django 4.1.3 on 2022-12-04 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_rename_teacher_lesson_teacher_id_lesson_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(default='student', max_length=15),
        ),
    ]
