# Generated by Django 4.1.2 on 2022-11-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_lessons_delete_invoice_alter_admin_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=30)),
                ('availability', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('interval', models.IntegerField()),
                ('topic', models.CharField(default='', max_length=20)),
                ('teacher_id', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
