# Generated by Django 4.1.3 on 2022-12-06 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_rename_teacher_id_request_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='availibility',
            field=models.DateField(null=True, verbose_name='enter your start date for the lessons (yyyy-mm-dd)'),
        ),
    ]
