# Generated by Django 4.1.2 on 2022-11-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_requests'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiceNum', models.CharField(max_length=30)),
                ('referNum', models.CharField(max_length=30)),
            ],
        ),
    ]
