# Generated by Django 4.1.3 on 2022-12-07 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_alter_request_availibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
