# Generated by Django 4.1.2 on 2022-11-22 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_availability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availability',
            old_name='date',
            new_name='date_field',
        ),
    ]
