# Generated by Django 4.1.2 on 2022-11-22 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0009_rename_date_availability_date_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availability',
            old_name='date_field',
            new_name='date',
        ),
    ]
