# Generated by Django 4.1.2 on 2022-11-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0010_rename_date_field_availability_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requests',
            name='availability',
        ),
        migrations.AddField(
            model_name='availability',
            name='request_id',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
