# Generated by Django 4.1.2 on 2022-11-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0011_remove_requests_availability_availability_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='request_id',
            field=models.CharField(default='', max_length=30),
        ),
    ]
