# Generated by Django 4.1.3 on 2022-11-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0012_alter_availability_request_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=30)),
                ('duration', models.IntegerField()),
                ('interval', models.IntegerField()),
                ('topic', models.CharField(default='', max_length=20)),
                ('teacher_id', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.RenameModel(
            old_name='Lessons',
            new_name='Lesson',
        ),
        migrations.DeleteModel(
            name='Requests',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='request_id',
        ),
        migrations.AddField(
            model_name='request',
            name='availability',
            field=models.ManyToManyField(to='lessons.availability'),
        ),
    ]
